### ISSUE TITLE
[OpenCV Library] When user runs SHAFT_Engine latest version at Jenkins CI server error related to open CV library occurs 

### ISSUE THREAD

**Issue by magdyheiba** [MohabMohie/SHAFT_ENGINE#130]
**Describe the bug**
When user runs SHAFT_Engine latest version at Jenkins error related to open CV library 

**To Reproduce**
Steps to reproduce the behaviour:
1. upgrade your project to the latest version 4.2.20200529
2- push it to any Source Code Management like github ...etc 
3-  pull from SCM and run the job 
4- check the result

**Expected behavior**
the job should be run and executed normally without problems 

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - Browser [chrome]
 - SHAFT_Engine Version [4.2.20200529]
![153](https://user-images.githubusercontent.com/38945724/84148155-d8d97880-aa5e-11ea-85b9-d152f1829f20.PNG)

![154](https://user-images.githubusercontent.com/38945724/84148167-db3bd280-aa5e-11ea-96e2-f792896c574c.PNG)

[generatedReport_20200609-133525.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4752166/generatedReport_20200609-133525.zip)

**Additional context**
1. is jenkins executing locally or via selenium grid?
**Locally on Linux server**
2. is this working for local execution or also not working?
**yes it is working fine and normally**

**Comment by MohabMohie** [comment]
please note that the attached zip file doesn't show the described error, hence I will try to go for a dry fix and push it in the next release.

**Comment by MohabMohie** [comment]
Fixed and will be released in the next version

**Comment by magdyheiba** [comment]
The issue still exists on Version 4.3.20200629 and kindly check the generated allure-report 
[generatedReport_20200719-120121.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4943545/generatedReport_20200719-120121.zip)

**Comment by MohabMohie** [comment]
@magdyheiba I think the archive is corrupted. would you kindly reupload?

**Comment by magdyheiba** [comment]
[generatedReport_20200719-120121.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4946127/generatedReport_20200719-120121.zip)

This is the one on the server if it is corrupted for the third time then there is something wrong with generating the archive because I just downloaded it

**Comment by MohabMohie** [comment]
it makes sense that you actually confirm that a file works before uploading it as an attachment to an issue @magdyheiba 
furthermore... archive generation doesn't work for jenkins execution, jenkins creates its own archive if you're using the allure reporting plugin.
lastly, just a couple of screenshots like the ones in the initial issue will be sufficient, also add one of the line of code and some context as to when that happens for you please.

**Comment by magdyheiba** [comment]
![319](https://user-images.githubusercontent.com/38945724/87927004-ce10fb00-ca82-11ea-8c01-ddfb6e359963.PNG)
![318](https://user-images.githubusercontent.com/38945724/87927010-cf422800-ca82-11ea-893a-2b51427fd567.PNG)


for the Code, it is a simple method to verify the inputs like this:-
![320](https://user-images.githubusercontent.com/38945724/87927225-2b0cb100-ca83-11ea-98e4-44ff5da0ce3e.PNG)

and for execution.properties :
screenshotParams_highlightMethod=AI

**Comment by MohabMohie** [comment]
I'm unable to reproduce this case on my jenkins server... local jenkins + mvn running on windows, linux-based docker-compose selenium grid, github sc
![image](https://user-images.githubusercontent.com/19201898/88318485-121e2d00-cd1b-11ea-91c6-1462b2d79026.png)

It's also working for github actions... mvn running on linux-based docker, linux-based docker-compose selenium grid, github sc
![image](https://user-images.githubusercontent.com/19201898/88318667-5ad5e600-cd1b-11ea-8731-2d314285adaf.png)

I don't know why this issue is happening from your side but I can't reproduce it... maybe it's some kind of environment issue?

for now please change the highlighting method to use javascript instead of opencv and let's setup a zoom meeting to discuss this case further. I'll close the defect as an environment issue and we can reopen it if an issue with the code was found.
